services:
  custom-nginx:
    build: ./api_gateway
    ports:
      - 3005:80
    networks:
      - mod-network

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules # Anonymous Volume
    networks:
      - mod-network

  module-service:
    build: ./backend/ModuleService
    ports:
      - 3001:3001
    volumes:
      - ./backend/ModuleService:/app
      - /app/node_modules # Anonymous Volume
    networks:
      - mod-network
  
  review-service:
    build: ./backend/ReviewService
    ports:
      - 3002:3002
    volumes:
      - ./backend/ReviewService:/app
      - /app/node_modules # Anonymous Volume
    networks:
      - mod-network
  
  prometheus-service:
    image: prom/prometheus:v2.20.1
    ports:
      - "9090:9090"
    volumes:
      - ./backend/ModuleService/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - mod-network
      
  grafana-service:
    image: grafana/grafana:7.1.5
    ports:
      - "3003:3000"
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./backend/ModuleService/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    networks:
      - mod-network

networks:
  mod-network:
    driver: bridge
